### ISSUE TITLE
Declarative implementation

### ISSUE THREAD

**Issue by Plecra** [Emoun/tt-equal#1]
With macro_rules, we can lean on the compiler to handle the actual comparison between the trees

```rust
#[doc(hidden)]
#[macro_export]
macro_rules! private_tt_equal {
    {
        $caller:tt
        dol = [{ $_:tt }]
        input = [{ $a:tt $b:tt }]
    } => {
        macro_rules! helper {
            {$a} => {tt_call::tt_return! {
                $caller
                is_equal = [{true}]
            }};
            {$__:tt} => {tt_call::tt_return! {
                $caller
                is_equal = [{false}]
            }};
        }
        helper!{$b}
    }
}
#[macro_export]
macro_rules! tt_equal {
    {
        $caller:tt
        input = [{ $a:tt $b:tt }]
    } => {
        $crate::private_tt_equal! {
            $caller
            dol = [{ $ }]
            input = [{ $a $b }]
        }
    };
}
```

**Comment by Plecra** [comment]
As far as I can tell, this locks the caller to item position, breaking the tt_call convention

**Comment by Emoun** [comment]
@Plecra just to be clear I'm assuming this is not a bug report for `tt_equal` but a discussion on implementation possibilities. 

It has been quite some time since I implemented this crate, so I don't remember the details and can't really comment on your code.

**Comment by Plecra** [comment]
That's right :) There's no problem with the code as it is
